# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gabor_Filter_Bank <- function(u, v, m, n, plot_data = FALSE) {
    .Call(`_OpenImageR_Gabor_Filter_Bank`, u, v, m, n, plot_data)
}

Gabor_export_Features <- function(img, d1, d2, u, v, m, n, downsample_vec = FALSE, plot_data = FALSE, normalize_features = FALSE, threads = 1L, vectorize_magnitude = TRUE) {
    .Call(`_OpenImageR_Gabor_export_Features`, img, d1, d2, u, v, m, n, downsample_vec, plot_data, normalize_features, threads, vectorize_magnitude)
}

Gabor_generate <- function(img_data, img_nrow, img_ncol, d1, d2, u, v, m, n, downsample_vec = FALSE, normalize_features = FALSE, threads = 1L) {
    .Call(`_OpenImageR_Gabor_generate`, img_data, img_nrow, img_ncol, d1, d2, u, v, m, n, downsample_vec, normalize_features, threads)
}

average_hash_string <- function(gray_image, hash_size = 8L, resize_method = "nearest") {
    .Call(`_OpenImageR_average_hash_string`, gray_image, hash_size, resize_method)
}

average_hash_binary <- function(gray_image, hash_size = 8L, resize_method = "nearest") {
    .Call(`_OpenImageR_average_hash_binary`, gray_image, hash_size, resize_method)
}

phash_string <- function(gray_image, hash_size = 8L, highfreq_factor = 4L, resize_method = "nearest") {
    .Call(`_OpenImageR_phash_string`, gray_image, hash_size, highfreq_factor, resize_method)
}

phash_binary <- function(gray_image, hash_size = 8L, highfreq_factor = 4L, resize_method = "nearest") {
    .Call(`_OpenImageR_phash_binary`, gray_image, hash_size, highfreq_factor, resize_method)
}

binary_to_hex <- function(x) {
    .Call(`_OpenImageR_binary_to_hex`, x)
}

dhash_string <- function(gray_image, hash_size = 8L, resize_method = "nearest") {
    .Call(`_OpenImageR_dhash_string`, gray_image, hash_size, resize_method)
}

dhash_binary <- function(gray_image, hash_size = 8L, resize_method = "nearest") {
    .Call(`_OpenImageR_dhash_binary`, gray_image, hash_size, resize_method)
}

hash_image <- function(x, new_width, new_height, resize_method, hash_size = 8L, highfreq_factor = 4L, method = 1L, threads = 1L) {
    .Call(`_OpenImageR_hash_image`, x, new_width, new_height, resize_method, hash_size, highfreq_factor, method, threads)
}

hash_image_cube <- function(x, resize_method, hash_size = 8L, highfreq_factor = 4L, method = 1L, threads = 1L) {
    .Call(`_OpenImageR_hash_image_cube`, x, resize_method, hash_size, highfreq_factor, method, threads)
}

hash_image_hex <- function(x, new_width, new_height, resize_method, hash_size = 8L, highfreq_factor = 4L, method = 1L, threads = 1L) {
    .Call(`_OpenImageR_hash_image_hex`, x, new_width, new_height, resize_method, hash_size, highfreq_factor, method, threads)
}

hash_image_cube_hex <- function(x, resize_method, hash_size = 8L, highfreq_factor = 4L, method = 1L, threads = 1L) {
    .Call(`_OpenImageR_hash_image_cube_hex`, x, resize_method, hash_size, highfreq_factor, method, threads)
}

levenshtein_dist <- function(s, t) {
    .Call(`_OpenImageR_levenshtein_dist`, s, t)
}

hog_cpp <- function(image, n_divs = 3L, n_bins = 6L) {
    .Call(`_OpenImageR_hog_cpp`, image, n_divs, n_bins)
}

list_2array_convert <- function(x) {
    .Call(`_OpenImageR_list_2array_convert`, x)
}

HOG_array <- function(x, n_divs = 3L, n_bins = 6L, threads = 1L) {
    .Call(`_OpenImageR_HOG_array`, x, n_divs, n_bins, threads)
}

HOG_matrix <- function(x, height, width, n_divs = 3L, n_bins = 6L, threads = 1L) {
    .Call(`_OpenImageR_HOG_matrix`, x, height, width, n_divs, n_bins, threads)
}

Rgb_2gray <- function(RGB_image) {
    .Call(`_OpenImageR_Rgb_2gray`, RGB_image)
}

conv2d <- function(image, kernel, mode) {
    .Call(`_OpenImageR_conv2d`, image, kernel, mode)
}

conv3d <- function(image, kernel, mode) {
    .Call(`_OpenImageR_conv3d`, image, kernel, mode)
}

Normalize_array <- function(x) {
    .Call(`_OpenImageR_Normalize_array`, x)
}

Normalize_matrix <- function(x) {
    .Call(`_OpenImageR_Normalize_matrix`, x)
}

rotate_nearest_bilinear <- function(image, angle, method, mode, threads) {
    .Call(`_OpenImageR_rotate_nearest_bilinear`, image, angle, method, mode, threads)
}

rotate_nearest_bilinear_array_same <- function(src, angle, method, threads) {
    .Call(`_OpenImageR_rotate_nearest_bilinear_array_same`, src, angle, method, threads)
}

rotate_nearest_bilinear_array_full <- function(src, angle, method, threads) {
    .Call(`_OpenImageR_rotate_nearest_bilinear_array_full`, src, angle, method, threads)
}

rotate_rcpp <- function(image, angle) {
    .Call(`_OpenImageR_rotate_rcpp`, image, angle)
}

resize_nearest_array <- function(image, width, height) {
    .Call(`_OpenImageR_resize_nearest_array`, image, width, height)
}

bilinear_array <- function(image, width, height) {
    .Call(`_OpenImageR_bilinear_array`, image, width, height)
}

resize_nearest_rcpp <- function(image, width, height) {
    .Call(`_OpenImageR_resize_nearest_rcpp`, image, width, height)
}

resize_bilinear_rcpp <- function(image, width, height) {
    .Call(`_OpenImageR_resize_bilinear_rcpp`, image, width, height)
}

im_flip <- function(x, mode = 1L) {
    .Call(`_OpenImageR_im_flip`, x, mode)
}

im_flip_cube <- function(src, mode = 1L) {
    .Call(`_OpenImageR_im_flip_cube`, src, mode)
}

zca_whitening <- function(data, k, epsilon) {
    .Call(`_OpenImageR_zca_whitening`, data, k, epsilon)
}

zca_whiten_cube <- function(src, k, epsilon) {
    .Call(`_OpenImageR_zca_whiten_cube`, src, k, epsilon)
}

diate_erode <- function(image, Filter, method = 1L, threads = 1L) {
    .Call(`_OpenImageR_diate_erode`, image, Filter, method, threads)
}

diate_erode_cube <- function(image, Filter, method = 1L, threads = 1L) {
    .Call(`_OpenImageR_diate_erode_cube`, image, Filter, method, threads)
}

translation_mat <- function(image, shift_rows = 0L, shift_cols = 0L, FILL_VALUE = 0.0) {
    .Call(`_OpenImageR_translation_mat`, image, shift_rows, shift_cols, FILL_VALUE)
}

augment_transf <- function(image, flip_mode, crop_height, crop_width, resiz_width = 0.0, resiz_height = 0.0, resiz_method = "nearest", shift_rows = 0.0, shift_cols = 0.0, rotate_angle = 0.0, rotate_method = "nearest", zca_comps = 0L, zca_epsilon = 0.0, image_thresh = 0.0, pad_shift_value = 0.0) {
    .Call(`_OpenImageR_augment_transf`, image, flip_mode, crop_height, crop_width, resiz_width, resiz_height, resiz_method, shift_rows, shift_cols, rotate_angle, rotate_method, zca_comps, zca_epsilon, image_thresh, pad_shift_value)
}

augment_transf_array <- function(image, flip_mode, crop_height, crop_width, pad_shift_value, resiz_width = 0.0, resiz_height = 0.0, resiz_method = "nearest", shift_rows = 0.0, shift_cols = 0.0, rotate_angle = 0.0, rotate_method = "nearest", zca_comps = 0L, zca_epsilon = 0.0, image_thresh = 0.0) {
    .Call(`_OpenImageR_augment_transf_array`, image, flip_mode, crop_height, crop_width, pad_shift_value, resiz_width, resiz_height, resiz_method, shift_rows, shift_cols, rotate_angle, rotate_method, zca_comps, zca_epsilon, image_thresh)
}

augment_array_list <- function(x, flip_mode, crop_height, crop_width, pad_shift_value, resiz_width = 0.0, resiz_height = 0.0, resiz_method = "nearest", shift_rows = 0.0, shift_cols = 0.0, rotate_angle = 0.0, rotate_method = "nearest", zca_comps = 0L, zca_epsilon = 0.0, image_thresh = 0.0) {
    .Call(`_OpenImageR_augment_array_list`, x, flip_mode, crop_height, crop_width, pad_shift_value, resiz_width, resiz_height, resiz_method, shift_rows, shift_cols, rotate_angle, rotate_method, zca_comps, zca_epsilon, image_thresh)
}

MinMaxMatrix <- function(x) {
    .Call(`_OpenImageR_MinMaxMatrix`, x)
}

MinMaxArray <- function(x) {
    .Call(`_OpenImageR_MinMaxArray`, x)
}

Array_range <- function(x, mode = 1L) {
    .Call(`_OpenImageR_Array_range`, x, mode)
}

meshgrid_y <- function(rows, cols) {
    .Call(`_OpenImageR_meshgrid_y`, rows, cols)
}

meshgrid_x <- function(rows, cols) {
    .Call(`_OpenImageR_meshgrid_x`, rows, cols)
}

rgbtolab <- function(rgb) {
    .Call(`_OpenImageR_rgbtolab`, rgb)
}

RGB_to_hsv <- function(x) {
    .Call(`_OpenImageR_RGB_to_hsv`, x)
}

interface_superpixels <- function(input_image, method = "slic", num_superpixel = 200L, compactness_factor = 20, return_slic_data = FALSE, return_lab_data = FALSE, return_labels = FALSE, write_slic = "", verbose = FALSE) {
    .Call(`_OpenImageR_interface_superpixels`, input_image, method, num_superpixel, compactness_factor, return_slic_data, return_lab_data, return_labels, write_slic, verbose)
}

spix_bbox <- function(spix_labels, non_overlapping_superpixels = FALSE) {
    .Call(`_OpenImageR_spix_bbox`, spix_labels, non_overlapping_superpixels)
}

spix_bbox_vector <- function(spix_labels, spix_labels_vec) {
    .Call(`_OpenImageR_spix_bbox_vector`, spix_labels, spix_labels_vec)
}

pad_matrix <- function(x, new_rows, new_cols, fill_value = 0.0) {
    .Call(`_OpenImageR_pad_matrix`, x, new_rows, new_cols, fill_value)
}

LOAD_data <- function(write_slic, type = "2d") {
    .Call(`_OpenImageR_LOAD_data`, write_slic, type)
}

get_affine_transform <- function(original_points, transformed_points) {
    .Call(`_OpenImageR_get_affine_transform`, original_points, transformed_points)
}

warpAffine_2d <- function(img, M, R, C, threads = 1L) {
    .Call(`_OpenImageR_warpAffine_2d`, img, M, R, C, threads)
}

warp_affine_3d <- function(img, M, R, C) {
    .Call(`_OpenImageR_warp_affine_3d`, img, M, R, C)
}

